adds support for Drupal 10
localgovdrupal/localgov_microsites_colour_picker_fields pull request #14
Opened 2023-01-20 16:25 UTC by markconroy

Closes #9

2023-01-21 10:23 UTC, finnlewis approved these changes

2023-01-23 14:27 UTC, finnlewis commented
@stephen-cox asks if this has been tested with Drupal 10.

- Would be good to install it in a Drupal 9 site and run the update status module.
- Install on a Drupal 10 site
- Confirm any tests are running.

2023-01-24 10:55 UTC, msayoung approved these changes

2023-01-25 15:34 UTC, stephen-cox requested changes
This doesn't install because the Drupal core version is also specified in the composer.json file:

https://github.com/localgovdrupal/localgov_microsites_colour_picker_fields/blob/73c1609eae734f59ef42ddba901b0614d7387027/composer.json#L7

Will look at fixing it

2023-01-25 15:44 UTC, stephen-cox approved these changes
I've tested this with the Upgrade Status module and installed successfully in a Drupal 10 site (although I haven't tested the functionality). Happy to approve on this basis.

2023-01-30 14:33 UTC, merged